openppl-public/ppq

ppq/IR/morph.py
There are some bugs with current Batchnorm merge logic. This bug crashs network parsing.
Here we create a hotfix for it. more formal patches will be upload later.
=> Fix Bug with BN merge

README.md
1. update wheel link maintained in pypi
2. add pip install in README
=> add pip install and wheel link

README.md, ppq/IR/morph.py, ppq/core/common.py, ppq/core/config.py, ppq/core/quant.py, ppq/parser/__init__.py, ppq/parser/onnxruntime_exporter.py
Support ONNXRuntime Quant&Dequant Format.
=> Update to 0.6.1

ppq/parser/onnxruntime_exporter.py
1. 在onnxruntime exporter导出时dump_graph_to_file函数里添加compel_joint_var=False可关闭强制联合定点
```python
dump_graph_to_file(file_path, config_path, TargetPlatform.ONNXRUNTIME, quantizer._graph, compel_joint_var=False)
```
2. 修复导出variable没有量化参数的问题
=> fix onnxruntime export

ppq/utils/attribute.py
=> fix conv auto_pads bugs

ppq/quantization/algorithm/training.py
remove annotation imports in case of incompatibility in previous python versions
=> remove annotations import

ProgramEntrance.py, ppq/IR/morph.py, ppq/api/interface.py, ppq/api/setting.py, ppq/executor/op/torch/default.py, ppq/executor/op/torch/shape.py, ppq/parser/caffe_exporter.py, ppq/quantization/algorithm/equalization.py, ppq/quantization/optim/base.py, ppq/quantization/optim/calibration.py, ppq/quantization/optim/ssd.py, ppq/quantization/quantizer/base.py, ppq/utils/fetch.py
* fix bugs with interface.
* fix bugs with caffe exporter.
* fix bugs with slice operation.
* refine some torch api invoking, so that it supports legacy torch version(1.6.0).
=> bug fixing of 0.6.3

ppq/csrc/cuda/train.cu
=> Fix with train.cu

Util.py
Fixed quantized function not being able to modify Calib Steps
=> fix bugs: fixed calib_steps

.github/workflows/ppq_simulator.yml
=> add ppq simulator CI test

ppq/quantization/quantizer/DSPQuantizer.py
Add reshape op to DSP quant_operation_types
=> Add reshape op to DSP quant_operation_types

tests/test_block.py, tests/test_system.py, tests/tscheme/base.py
=> modify ci test

ppq/parser/matex_exporter.py, ppq/quantization/optim/refine.py
- fix extra [] in quant alignment 
- fix activation op removing in metax exporter
=> fix metax export

md_doc/basic/FlexiableUse.md, md_doc/basic/ProgramEntrance.md
add some basic usage markdown documents
=> add markdown doc

ppq/IR/morph.py
1. add ConvTranspose-Bn fold
2. correct Gemm-Bn fold
=> add bn fold support for ConvTranspose

ppq/executor/op/torch/default.py
=> fix resize op

ppq/IR/base/command.py, ppq/IR/base/graph.py, ppq/IR/morph.py, ppq/api/interface.py, ppq/api/setting.py, ppq/core/data.py, ppq/executor/op/torch/default.py, ppq/parser/matex_exporter.py, ppq/parser/onnxruntime_exporter.py, ppq/parser/tensorRT.py, ppq/quantization/optim/base.py, ppq/quantization/optim/morph.py, ppq/quantization/optim/training.py, ppq/quantization/quantizer/base.py
* 重做计算图操作接口
* 重做 onnxruntime 导出逻辑
* 添加 gru 量化支持与 gru 分解
* 修正 matex gemm split pass 的 bug
* 加速 lsq 算法执行
* 添加 mod 算子支持
* 添加了几个api函数，现在允许你手动控制优化逻辑。
=> 0.6.4 Update - 2

md_doc/basic/ProgramEntrance.md, ppq/executor/op/torch/default.py, ppq/quantization/optim/ssd.py
1. add softplus execution
2. fix some typo error in docs
=> add softplus & fix typo

ppq/csrc/cuda/train.cu
有些时候编译器通不过这个sqrt的函数调用，这个pr将修复上述问题
=> 修改了 train.cu 中的 sqrt 函数调用，将它们变为 sqrtf

ppq/api/setting.py, ppq/log/logger.py, ppq/quantization/optim/training.py, ppq/quantization/quantizer/base.py
1. simplify lsq by providing fewer options
2. add property check for lsq & brecq
=> simplify lsq & add property check

ppq/quantization/optim/__init__.py, ppq/quantization/optim/refine.py, ppq/quantization/quantizer/NCNNQuantizer.py
1. remove Split & Output quantization in ncnn quantizer for alignement with backend
2. add scale unify requantize pass
=> refine ncnn quantizer & add scale unify pass

ppq/parser/ncnn_exporter.py
仅探讨：
应由调用方保证名字是对的，给啥就是啥。
不应该偷偷加后缀。
=> feat(export): remove suffix

md_doc/inference_with_ncnn.md, md_doc/inference_with_ppl_cuda.md
1. add ncnn inference doc
2. add ppl cuda inference doc
=> add backend inference doc

ppq/executor/torch.py, ppq/quantization/optim/calibration.py
* 改成尽力匹配。如果 inputs 多写了几个 key 只报错提醒不崩溃。之前 check 太严格了。
* 继续 fix typo
=> improvement(executor/torch.py): support more input type and fix typo

md_doc/inference_with_ncnn.md, md_doc/inference_with_ppl_cuda.md, ppq/log/logger.py, ppq/quantization/optim/training.py
1. add brecq power-of-2 act scale tuning check
2. prettify log style
3. fix doc mistake
=> fix doc & log style

md_doc/inference_with_ncnn.md, md_doc/inference_with_ppl_cuda.md, ppq/parser/ncnn_exporter.py
1. fix some mistakenly copy-paste errors in markdown doc
2. generalize ncnn export model formats(with suffix or not)
=> amend doc details

ppq/samples/Imagenet/Utilities/Imagenet/__init__.py, ppq/samples/Imagenet/Utilities/Imagenet/imagenet_util.py, ppq/samples/Imagenet/Utilities/__init__.py, ppq/samples/Imagenet/evaluation_with_imagenet.py
=> Add Imagenet Samples

ppq/IR/base/graph.py, ppq/IR/deploy.py, ppq/executor/op/torch/default.py, ppq/parser/caffe/caffe_import_utils.py, ppq/parser/onnx_exporter.py, ppq/parser/onnx_parser.py, ppq/quantization/optim/refine.py, ppq/quantization/quantizer/NCNNQuantizer.py, ppq/scheduler/base.py
1. add execution support for opset13
2. add opset parse for operation in onnx parser
3. add axis parse for omitted reshape operation before inner product in Caffe
=> add opset 13 support

md_doc/how_to_use.md, ppq/parser/caffe/caffe_export_utils.py, ppq/quantization/quantizer/DSPQuantizer.py
1. fix the convTranspose axis for dsp ti
2. add Cuda kernel in how_to_use.md
3. add inner product axis export for caffe
=> fix dsp ti bug

ppq/executor/op/torch/default.py, ppq/executor/op/torch/shape.py
=> Add lessorequal and op

MANIFEST.in, ppq/core/quant.py, ppq/quantization/observer/range.py, ppq/quantization/quantizer/OpenvinoQuantizer.py
* 修正了一个MANIFEST.in 里面缺了点东西的问题。
* 把 openvino 的量化改成对称的了，好像跑的更快一点。
=> Update MANIFEST & openvino quant

ppq/executor/op/torch/default.py
modify shape of h / c to [squence_len, batch, hiddensize] when setting default value
=> Fix bug of LSTM 

ppq/quantization/optim/parameters.py
=> Fix bug with complex bias

ppq/IR/deploy.py, ppq/IR/morph.py, ppq/core/data.py, ppq/parser/onnx_exporter.py, ppq/parser/util.py, ppq/quantization/optim/training.py, ppq/quantization/quantizer/base.py
=> fix(src): spell error

ppq/IR/morph.py
修了一个将 matmul + add 算子fuse成 gemm的bug
=> update fuse gemm

ppq/executor/op/torch/default.py
上次改了又被 revert 掉了，什么个情况 ？   https://github.com/openppl-public/ppq/commit/8f351460b87817b4a0466e917c884ce7b13e854d
之前的 mha 计算过程是错的。
=> Update default.py (#172)

ppq/__init__.py
add import warning
reference: [torchvision](https://github.com/pytorch/vision/blob/main/torchvision/__init__.py#L15-L23)
=> add import warning

ppq/quantization/observer/range.py
=> fix kl device error

ppq/api/interface.py, ppq/parser/trt_exporter.py, ppq/quantization/quantizer/TensorRTQuantizer.py
增加'HardSwish', 'HardSigmoid'的量化参数
=> fix(20221010-trt-add-more-op-config)

ppq/samples/bypass_nms.py, ppq/samples/custimized_quant.py
Fix examples args and opset typo
=> Fix examples args and opset typo

ppq/samples/TensorRT/lenet_demo/CMakeLists.txt, ppq/samples/TensorRT/lenet_demo/common/ErrorRecorder.h, ppq/samples/TensorRT/lenet_demo/common/common.h, ppq/samples/TensorRT/lenet_demo/common/logger.cpp, ppq/samples/TensorRT/lenet_demo/common/logger.h, ppq/samples/TensorRT/lenet_demo/common/logging.h, ppq/samples/TensorRT/lenet_demo/common/macros.h, ppq/samples/TensorRT/lenet_demo/generate_onnx.py, ppq/samples/TensorRT/lenet_demo/lenet_int8.cpp, ppq/samples/TensorRT/lenet_demo/lenet_int8.py
=> 20221025-add-trt-quant

ppq/executor/op/torch/base.py, ppq/executor/op/torch/default.py
* 修复了 None value 作为算子输入时的一些 bug
=> Fix None value bug

ppq/IR/base/command.py, ppq/IR/morph.py, ppq/IR/quantize.py, ppq/api/interface.py, ppq/core/quant.py, ppq/executor/op/torch/default.py, ppq/parser/caffe_exporter.py, ppq/parser/matex_exporter.py, ppq/parser/onnx_exporter.py, ppq/parser/qnn_exporter.py
* 添加了 resize, pad 算子的规范化，他们将被直接升级到 opset 11
* 添加了有关 None value 的一些支持
=> 进一步修改以支持 None value

ppq/IR/base/graph.py, ppq/IR/morph.py, ppq/core/quant.py, ppq/executor/op/torch/default.py, ppq/parser/onnxruntime_exporter.py, ppq/parser/qnn_exporter.py, ppq/quantization/optim/base.py, ppq/quantization/optim/parameters.py, ppq/quantization/optim/refine.py, ppq/quantization/qfunction/linear.py, ppq/quantization/quantizer/DSPQuantizer.py, ppq/samples/Onnxruntime/Example_Benchmark.py, ppq/samples/Onnxruntime/Example_PTQ.py
=> 修改有关qnn的导出逻辑和量化逻辑

ppq/parser/ascend_export.py, ppq/parser/caffe_exporter.py, ppq/quantization/quantizer/AscendQuantizer.py
=> 1122-fix-ascend-quant

ppq/parser/onnx_exporter.py
=> 添加 Value Info

ppq/IR/morph.py
=> fix bn bug of deliver bn op in graph

ppq/api/setting.py, ppq/core/quant.py, ppq/lib/common.py, ppq/parser/__init__.py, ppq/parser/mnn_exporter.py, ppq/quantization/optim/refine.py, ppq/quantization/quantizer/MNNQuantizer.py, ppq/quantization/quantizer/__init__.py
=> 1229-add-mnn-quant

ppq/parser/qnn_exporter.py
=> add qnn caffe export

ppq/quantization/optim/refine.py
* 现在将对 Resize Op 进行输入/输出 scale 对齐
* 现在将对所有出现在 PASSIVE_OPERATIONS 中的非计算算子进行 scale 对齐，无需 Quantizer 进行设置
=> 添加针对 Resize Op 的对齐策略，修改 Passive Op 的处理策略

ppq/parser/mnn_exporter.py, ppq/quantization/quantizer/MNNQuantizer.py
=> add mnn caffe export.

ppq/core/ffi.py, ppq/csrc/cuda/common.cuh, ppq/csrc/cuda/linear.cu, ppq/csrc/cuda/linear.h, ppq/lib/quant.py, tests/test_cuda_kernel.py
更新 Cuda kernel 的实现，新的实现将进一步提速 PPQ 的执行性能。
更新 Cuda kernel 的测试脚本。
修正了一个LinearQuantizationConfig创建时的bug
=> Update Cuda kernel & Test Cases

ppq/parser/qnn_exporter.py
修正了在一些情况下，softmax 与 sigmoid 的量化参数不应被修改的问题。
=> Fix a bug of QNN Exporter

ppq/quantization/algorithm/training.py
修复了一个BlockBuilder在一些情况下，无法正确寻找到end point的问题
=> 修复了一个BlockBuilder中的问题

ppq/samples/Tutorial/bestPractice.py
=> fix bestPractice.py

ProgramEntrance_2.py, ppq/parser/onnxruntime_exporter.py, ppq/quantization/optim/refine.py
=> Fix exporter bugs

ppq/parser/onnxruntime_exporter.py
新的 onnx checker 会对 ai.onnx 这个 domain 报错，这个补丁将其修改为 ""
=> 修正了一个 onnx domain 的相关问题
