ppq/quantization/optim/training.py
This PR tries to replace `adaquant_xxx` with `adaround_xxx` in `AdaRoundPass`. To be fair it is a trivial difference and wouldn't alter any code behaviour. But to be strict, [AdaRound](https://arxiv.org/pdf/2004.10568.pdf) and [AdaQuant](https://arxiv.org/pdf/2006.10518.pdf) are two algorithms, mix-use could be a little bit confusing.
=> RENAME AdaQuant to AdaRound

ppq/quantization/quantizer/NXPQuantizer.py
overload `build_quant_pipeline` for `NXP_Quantizer`. `create_optim_pipeline_from_setting` doesn't have any reference in codebase.
=> overload NXP build_quant_pipeline

ppq/quantization/algorithm/equalization.py
Also, it makes calling conversion consistent with other files.
=> let permute in equalization.py compatable with lower torch version

ppq/IR/base/graph.py, ppq/api/__init__.py, ppq/core/common.py, ppq/core/quant.py, ppq/executor/base.py, ppq/executor/op/__init__.py, ppq/executor/op/torch/__init__.py, ppq/executor/op/torch/default.py, ppq/executor/op/torch/onnx.py, ppq/parser/__init__.py, ppq/parser/onnx_exporter.py, ppq/parser/onnxruntime_oos_exporter.py, ppq/quantization/optim/refine.py, ppq/quantization/quantizer/ORTQuantizer.py, ppq/quantization/quantizer/__init__.py, ppq/scheduler/dispatchers.py
This PR adds an MVP implementation of quantized ONNX model exporter with operator oriented style (OOS). It supports QLinear ops including `QLinearConv`, `QLinearAdd`, `QLinearMul`, `QLinearMatMul`, `QLinearGlobalAveragePool` and `QLinearAveragePool`. The elimination(fusion) of `Clip` and `Relu` is also supported. More ops might be added in the future.
This PR also implements two ORT quantizers (per-tensor and per-channel). ORTQuantizer + ORTExporter combination has been tested on ResNet18, ResNet50 and MobileNet V2 (flatten version), with a very small calibration dataset(~8) on CPU. The steps are:
1. Fix a backbone
2. Fix a quantizer (ORT per-channel or ORT per-tensor)
3. Do calibration with the same dataset, export with both `ONNXRUNTIMExporter` and `ORTOOSExporter`, get model A and …
=> (feature): add onnx quantizer and oos exporter

ppq/api/interface.py
上一次对Dispatcher修改导致参数传递错误，所有Shape算子的调度平台出现错误。这个commit将会修复这些错误。
=> Fix Critical Failure of Dispatcher

ppq/core/quant.py
在TensorQuantizationConfig.copy函数中，错误地对detail字典进行了直接赋值操作，这使得复制出来的config对象与原对象共享对detail字典的访问。
=> Fix a bug with TensorQuantizationConfig.copy

ppq/IR/base/graph.py, ppq/IR/morph.py, ppq/IR/quantize.py, ppq/api/interface.py, ppq/api/setting.py, ppq/core/config.py, ppq/core/data.py, ppq/core/ffi.py, ppq/core/quant.py, ppq/csrc/cuda/linear.cu, ppq/csrc/cuda/linear.h, ppq/csrc/cuda/sort.cu, ppq/csrc/cuda/train.cu, ppq/executor/base.py, ppq/parser/__init__.py, ppq/parser/matex_exporter.py, ppq/parser/onnxruntime_exporter.py, ppq/parser/onnxruntime_oos_exporter.py, ppq/parser/tensorRT.py, ppq/quantization/algorithm/training.py, ppq/quantization/optim/__init__.py, ppq/quantization/optim/morph.py, ppq/quantization/optim/parameters.py, ppq/quantization/optim/training.py, ppq/quantization/qfunction/linear.py, ppq/quantization/quantizer/GRUQuantizer.py, ppq/quantization/quantizer/MyQuantizer.py, ppq/quantization/quantizer/base.py
* 重写了 TensorRT 的导出逻辑，现在PPQ使用 onnx qdq 格式直接导出engine
* 重写了 onnxruntime 导出逻辑
* 完善了 lsq 算法与 Qdrop 的 cuda 实现，现在它们还有一些问题，我们将在0.6.4的后续更新中将其加入advanced optimization pass
* 修改了 adavanced optimization 逻辑，现在不启动cuda kernel的情况下不允许使用这个pass
* 对创建 TensorMeta 的过程添加了检查，现在不允许以空类型创建TensorMeta
* 修改了cuda kernel的报错字符串，现在它更容易读懂了一些。
---
* 添加了MetaxExporter
* 添加了WeightSplitPass
* 添加了一个新的量化平台HEXAGON_INT8 = 801，我们将在这个平台上尝试量化GRU
* 添加了操作计算图的函数insert_op_between_var_and_op
* 添加了GraphDecomposer类，我们将在 0.6.4 的后续更新中使用这个类完成算子分解任务
=> Core Update to 0.6.4

ppq/quantization/optim/parameters.py
执行concat强制联合定点时，如果网络结构复杂，有可能将conv, gemm等算子的输入或输出状态置为 SLVAE，这种情况下被动量化将会产生错误。
=> 修复了一个由强制联合定点引起的罕见错误

ppq/api/interface.py, ppq/executor/base.py, ppq/executor/op/torch/default.py, ppq/executor/op/torch/shape.py, ppq/parser/onnxruntime_exporter.py, ppq/parser/tensorRT.py, ppq/quantization/observer/range.py, ppq/quantization/quantizer/AcademicQuantizer.py, ppq/quantization/quantizer/DSPQuantizer.py, ppq/quantization/quantizer/FPGAQuantizer.py, ppq/quantization/quantizer/MetaxQuantizer.py, ppq/quantization/quantizer/MyQuantizer.py, ppq/quantization/quantizer/NCNNQuantizer.py, ppq/quantization/quantizer/NXPQuantizer.py, ppq/quantization/quantizer/ORTQuantizer.py, ppq/quantization/quantizer/OpenvinoQuantizer.py, ppq/quantization/quantizer/PPLQuantizer.py, ppq/quantization/quantizer/TRTQuantizer.py, ppq/quantization/quantizer/base.py, ppq/samples/custimized_quant.py
* 添加了 'register_network_quantizer', 'register_network_parser', 'register_network_exporter', 'register_operation_handler'函数，你将使用这四个函数来完全自定义量化过程，为此我们添加了一个新的文件教你如何去做：ppq/samples/custimized_quant.py
* 添加了LogSoftmax_forward，ReduceSum_forward, GreaterOrEqual_forward
@tpoisonooo 你可以参考 custimized_quant.py 中的例子来完成复杂网络量化的支持，新的函数将使得自定义量化更加容易。
=> Support Custimize Everything.

README.md, ppq/IR/__init__.py, ppq/IR/base/graph.py, ppq/api/setting.py, ppq/core/common.py, ppq/quantization/optim/parameters.py, ppq/quantization/optim/refine.py
* 修改了默认量化策略，现在activation和parameter将默认采用quantizer的量化配置，而不是用setting中的算法覆盖它们的。
* 添加了一个叫做Opset的类型，现在还没什么用，未来我们将在这个数据结构的基础上支持opset13~opset11
* 将 relu 和 clip 的强制定点覆盖补充回来了
* 为 passive parameter的状态新增了检查
=> Fusion, Seting, Example Update

ppq/quantization/optim/training.py
fix a bug that lsq can not support collecting_device = 'cpu'
=> 修正了一个lsq不能使用cpu作为缓存设备的错误

ppq/parser/onnxruntime_exporter.py, ppq/parser/tensorRT.py, ppq/quantization/quantizer/TRTQuantizer.py, ppq/quantization/quantizer/base.py
* 解除trt导出时的限制，现在你可以导出任意qdq节点，不再仅限于导出计算节点的qdq信息
* 解除量化器的限制，现在允许你为非量化类型初始化量化信息(手动覆盖)
* 添加了一个 onnxruntime QDQ 导出时候的优化，可以合并不同分支上的 QDQ 节点，还在施工当中
=> 解除一些自定义量化规则的限制

README.md, ppq/IR/base/graph.py, ppq/api/interface.py, ppq/core/common.py, ppq/core/quant.py, ppq/parser/caffe_exporter.py, ppq/parser/ncnn_exporter.py, ppq/parser/nxp_exporter.py, ppq/parser/onnxruntime_exporter.py, ppq/parser/onnxruntime_oos_exporter.py, ppq/parser/ppl.py, ppq/quantization/algorithm/equalization.py, ppq/quantization/analyse/graphwise.py, ppq/quantization/optim/equalization.py, ppq/quantization/optim/parameters.py, ppq/quantization/optim/refine.py, ppq/quantization/qfunction/linear.py, ppq/quantization/quantizer/DSPQuantizer.py, ppq/quantization/quantizer/OpenvinoQuantizer.py, ppq/quantization/quantizer/base.py, ppq/samples/Tutorial/fusion.py, tests/test_layerwise_equalization.py
* 为dump_torch_to_onnx函数添加了默认参数
* EXPORT_OVERLAPPED_CONFIG 现在是过时参数，你将使用TQC上的QuantizationVisiblity属性来进行导出控制。该属性有三个可选项：强制导出、TQC激活时导出、不导出。
* 修改了 exporter 逻辑以适配新的QuantizationVisiblity属性
* 修改了onnx qdq的导出逻辑，现在将尽可能消除非对称量化中的激活函数。
* 修改了 graphwise analyser 的逻辑，现在允许分析多输出算子的误差
* 修改了 layerwise equalization 的逻辑，现在允许 include act，支持conv1d, conv2d conv3d, convtranpose1d, convtranspose2d, convtranspose3d, gemm, matmul
* 修复了 passive parameter pass 中的 pad 量化错误
* 修复了 quant alignment pass 中 pooling 算子的对齐错误
* 修复了 核心量化函数在启动 cuda kernel 的情况下无法处理 cpu tensor 的问题
* 修改 openvino 量化策略，负数部分现在可以取到-128(曾经是-127)
* 给 dsp quantizer 添加了一个新的量化类型
=> onnx 模型导出与算法更新

requirements.txt
when use onnx.save_model with arguments size_threshold, onnx <= 1.8.1 could not handle.
=> update onnx requirements support for save_model

ppq/executor/op/torch/default.py
当resize算子恰好有4个输入且第四个输入为空时，将可能引发错误。这个补丁修复了上述情况。
=> 修正了一个 resize_forward 可能发生的错误

ppq/parser/onnx_exporter.py
当torch.tensor中仅包含一个元素时，由此生成的np.ndarray是0维的。
进而导致onnx导出错误。
=> Fix bug of onnx export

ppq/csrc/cuda/linear.cu
语句 rsqrtf((float)(num_of_element * (clip_max - clip_min))); 
可能因为 num_of_element * (clip_max - clip_min) 出现符号溢出而导致结果错误，该补丁修复了上述问题。
=> 修复一个Cuda kernel中可能出现的严重错误

ppq/IR/base/graph.py
**Bug description**: The `input_var` and `output_var` defined in line 621 could be overwriten by the `removing_op.inputs` and `removing_op.outputs` iteration.
https://github.com/openppl-public/ppq/blob/c7c1aa877c7eec1dbcf08a8ef1750f963eafa0c6/ppq/IR/base/graph.py#L621-L640
**Bug fix**: rename the `input_var` and `output_var` in the iteration.
- `ppq/IR/base/graph.py`
- Fix the bug mentioned above.
- Update the code formart that modified by pre-commit.
=> [Fix] The input_var and ouptut_var in BaseGraph.remove_operation could be overwriten

ppq/samples/TensorRT/Example_Torch2trt.py
I find that there is no trace_handler in Example_Torch2trt.py, and I added one.
=> Add a trace_handler for Example_Torch2trt.py

ppq/IR/morph.py
* 现在反卷积与Batchnorm的合并支持1d, 2d, 3d卷积，过去只支持2d.
=> 修正了一个反卷积与Batchnorm进行合并时可能遇到的问题
